### PR TITLE
Remove highlight element when marker is removed from layer

### PR DESCRIPTION
**Pull request by lchanouha**

### CODE REVIEW

**Comment by lchanouha** [comment]
I forgot to commit index.js sorry... I will make a new pr...

**Comment by brandonxiang** [comment]
If you can test it in the example directory, I will appreciate that.

**Comment by lchanouha** [comment]
Yes sorry. Should I lib increase version number to 0.0.4 in the updated commit ?

**Comment by brandonxiang** [comment]
ok

**Pull request merged**
